### ISSUE TITLE
Control of photon emission rate looks odd

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#113]
In the process of instrumenting this sim for data collection (see #112), I've noticed that the way the sliders on the photon emitters control the emission rate is a little odd.  It looks like the sliders control a model property, which is called emissionFrequency but actually maps the the slider range, is then monitored in the slider class, which then calls back into the model via a method called setPhotonEmissionPeriod.  This could be much more straightforward.

**Comment by jessegreenberg** [comment]
I made a change to the way the emission rate is controlled, see comit above.  I moved property emissionFrequency out of the PhotonAbsorptionModel and into the PhotonEmitterNode.  Property emissionFrequency exists in PhotonEmitterNode so that it can be used for linear mapping of the PhotonEmitterNode opacity.

Range of the slider now runs from 0 to 1 instead of 0 to 100 so so that slider maps directly to the opacity.  Cases of ( emissionFrequency / 100 ) sprinkled throughout the code have been removed.  

Removing property emissionFrequency from the model means that it was also removed from the tandemSet.  Is this OK and does a new tandem instance for frequency need to be added in the PhotonEmitterNode?  I am not familiar with Tandem.  @jbphet would you mind reviewing this?

**Comment by jbphet** [comment]
I just tried adding emission frequency as a tandem entity, but it isn't working out so well, because when the period is infinite (meaning that the emitter is off), the value shown in the event stream is ```null```.  Apparently, infinity is not something that JSON can deal with, see http://stackoverflow.com/questions/16644597/json-stringify-converting-infinity-to-null.  Also, I don't really like logging the period instead of the frequency since I feel like it is harder for people to understand.  Looking back at the motivation for this change, the thing I had an issue with is that the frequency property in PhetAbsorptionModel was being set by the slider, which in turn was being watched by the slider, which was then calling back into PhetAbsorptionModel to set the emission period through the setPhotonEmissionMethod.  What should happen instead is that the emission period is just controlled locally inside of PhetAbsorptionModel.

@jessegreenberg - I think I gave you some poor guidance on this - my apologies.  I think we should restore the frequency property to PhotonAbsorptionModel and just make the linkage to the emission period internal to that class.  I'm assigning back to you for implementation, but feel free to put it back in my court if you're not clear on what I'm recommending and I'll take care of it.

**Comment by jessegreenberg** [comment]
Frequency Property is now back in the PhotonAbsorptionModel.  The tandem instance for emission frequency is back in the PhotonAbsorptionModel as well.

The map from photon emission frequency to period now exists exclusively in the PhotonAbsorptionModel.  Reassigning to @jbphet for review.

**Comment by jbphet** [comment]
Looks good.  I did some additional cleanup and, along the way, discovered that we were using seconds as the time base in some places and milliseconds in others.  This was corrected so that seconds are no used throughout the code.  @jessegreenberg was working with me as these changes were made, so no need for further review.  Closing.
