### ISSUE TITLE
phetio ids should not be formed using string concatenation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecules-and-light#165]
I ran into this while working on a similar issue, https://github.com/phetsims/tandem/issues/41.

In sonificationDefault.js, these lines all duplicate the '.' separator:

```js
76 var photonEmittedPropertyID = MODEL_PROPERTY_ID + '.photons';
96 var coMoleculeID = MODEL_PROPERTY_ID + '.CO.vibratingProperty';
107 coMoleculeID = MODEL_PROPERTY_ID + '.CO.rotatingProperty';
125 var moleculeID = MODEL_PROPERTY_ID + '.molecules';
143 var moleculePropertyID = MODEL_PROPERTY_ID + '.' + currentMolecule + '.vibratingProperty';
155 moleculePropertyID = MODEL_PROPERTY_ID + '.' + currentMolecule + '.rotatingProperty';
```

You should definitely _not_ be using string concatenation to form the `phetioID` to SimIFrameClient `invoke`, for the same reasons mentioned in https://github.com/phetsims/tandem/issues/41.

Assigning to @zepumph and @jbphet, since they are the first 2 authors listed.

**Comment by samreid** [comment]
I'd like to note that all commits on the file are from @briannatomlinson but it would be good for @pixelzoom @jbphet @zepumph and I to come up with a plan before we make a recommendation.

Let's discuss the big picture in https://github.com/phetsims/tandem/issues/41 and it will tell us how to proceed here.

**Comment by pixelzoom** [comment]
Hmmm... If all commits are from  @briannatomlinson, then the `@author` annotations also need to be fixed.

**Comment by samreid** [comment]
Unless it was copy/pasted from a different repo/author?

**Comment by zepumph** [comment]
I agree. I have not touched sonification on this Sim. I helped to create the framework for the first few sonification wrappers though. Perhaps a copy paste error.

**Comment by briannatomlinson** [comment]
Yeah, I might not have removed them when I copied the base text formatting
from RIAW for all of the first files for MAL. I can fix this next time I'm
at one of my pcs where github is installed. Didn't mean to cause confusion!

Just let me know what you'd like me to do w.r.t. the phetio ids (I was
trying to follow what John had been doing in other files, but maybe I
misunderstood)

On Dec 27, 2017 11:02 AM, "Michael Kauzmann" <notifications@github.com>
wrote:

I agree. I have not touched sonification on this Sim. I helped to create
the framework for the first few sonification wrappers though. Perhaps a
copy paste error.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/phetsims/molecules-and-light/issues/165#issuecomment-354134551>,
or mute the thread

**Comment by jbphet** [comment]
In the opening comment, @pixelzoom says:

> In sonificationDefault.js, these lines all duplicate the '.' separator

then
> You should definitely not be using string concatenation to form the `phetioID`

He then references https://github.com/phetsims/tandem/issues/41 for the explanation of why we shouldn't do this.  That issue is quite long, with dialog going back and forth between @pixelzoom and @samreid with a little bit of @zepumph thrown in.  The last comment in that issue at the moment is a request by @samreid for some review.  So, can someone please save us some time and clearly state what **should** be done in the wrappers, and point @briannatomlinson and me to a good example to follow?  Thanks.

**Comment by pixelzoom** [comment]
> So, can someone please save us some time and clearly state what should be done in the wrappers, and point @briannatomlinson and me to a good example to follow? Thanks.

Will do so as soon as the work on encapsulating ids is completed in phetsims/tandem#41. (That's why this issue isn't assigned to you yet.)

**Comment by pixelzoom** [comment]
Mea culpa, the issue was previously assigned to you.  Stand by for examples when phetsims/tandem#41 is completed.

**Comment by pixelzoom** [comment]
@jbphet Here's the summary and examples that you requested.

`PhetioIDUtils` encapsulates the creation and manipulation of phetioID.  It's preloaded and you access it as a global (like QueryStringMachine.js). 

Where sonificationDefault.js uses the separator literal ('.') and string concatenation, use `PhetioIDUtils.append` to form a phetioID.

Example diff:

```js
- 15  var SCREEN_PROPERTY_ID = 'moleculesAndLight.moleculesAndLightScreen' ;
+ 15  var SCREEN_PROPERTY_ID = PhetioIDUtils.append( 'moleculesAndLight', 'moleculesAndLightScreen' );
```

String concatenations that involve multiple occurrences of the separator ('.') in a single statement are a bit more work.  For example:

```js
143 var moleculePropertyID = MODEL_PROPERTY_ID + '.' + currentMolecule + '.vibratingProperty';
```

It's still possible to do this as a single assignment statement, but ugly and not particularly readable:

```js
143 var moleculePropertyID = PhetioIDUtils.append( PhetioIDUtils.append( MODEL_PROPERTY_ID, currentMolecule ), 'vibratingProperty' );
```

If it were me, I'd split this into 2 statements, like this:

```js
var moleculeID = PhetioIDUtils.append( MODEL_PROPERTY_ID, currentMolecule ); 
var vibratingPropertyID = PhetioIDUtils.append( moleculeID, 'vibratingProperty' );
```

PhetioIDUtils is certainly open to changes/additions, so feel free to propose (or add) additional methods needed by client code.

Let me know if you have any questions.

**Comment by pixelzoom** [comment]
While preparing the above examples, I also noted that these 3 constants:

```js
  var SCREEN_PROPERTY_ID = 'moleculesAndLight.moleculesAndLightScreen' ;
  var MODEL_PROPERTY_ID = SCREEN_PROPERTY_ID + '.model' ;
  //var VIEW_PROPERTY_ID = SCREEN_PROPERTY_ID + '.view' ;
```

... have misleading names.  These are not Property ids, the area simple the phetioID of the screen, model and view respectively.

**Comment by jbphet** [comment]
All of the current sonification wrappers use string concatenation for forming PhET-iO IDs.  I just checked the history of `PhetioIDUtils, and it was born yesterday (Dec 28, 2017), so I think this new requirement for not using string concatenation is a recent development (feel free to correct me if I'm wrong on this).  This begs the question of whether it is worth the time and effort to go back through the sonification wrappers and rework them.  So far, these wrappers have been used primarily for prototyping and demonstration purposes, and I wouldn't expect that most of them will live very long, since the ultimate goal is to move the sonification functionality into the mainline PhET sims.  These wrappers are not currently being shared with commercial customers of PhET-iO.

@samreid - I'd like your input on this.  Do you know of any plan to share these wrappers with commercial customers?  In your opinion, would it be sufficient to address this issue by saying we should use the `PhetioIDUtils` approach for creating IDs in sonification wrappers moving forward, and not going back and reworking the existing wrappers?

@briannatomlinson - it's probably a good idea to modify the MAL wrapper to use this approach, since it is the recommendation, and that wrapper is still in progress.  Let me know if you'd like help with it.

**Comment by pixelzoom** [comment]
@jbphet said:
> ... I think this new requirement for not using string concatenation is a recent development ...

If you're saying that it's a new requirement not to use anti-patterns for creating ids, then I agree.  But I'm having really difficult time understanding why no one recognizes that using string concatenation to form an id is a really bad idea (regardless of whether PhetioIDUtils existed) and why I'm getting so much push back on this.  Frankly, I'm about to drop it.

**Comment by jbphet** [comment]
@pixelzoom - I don't think you should drop it, and I appreciate that you brought it to the attention of those of us who are developing sonification wrappers.  Also, I don't really see what I've said as pushing back on the idea of avoiding string concatenation, I'm just trying to do an honest cost-benefit analysis of the time required to make these changes in the existing wrappers and the value that we would gain from doing so.

**Comment by pixelzoom** [comment]
Thanks for clarifying @jbphet, and sorry for venting in your direction.

**Comment by briannatomlinson** [comment]
I don't mind making the changes, I'll update MAL when I get back to Atlanta.

Thanks for all of the recommendations; I'm happy to follow whatever styling
and syntax PhET wants. (I'll make the other changes to the variable names
too!)

Brianna

On Dec 29, 2017 12:47 PM, "John B" <notifications@github.com> wrote:

@pixelzoom <https://github.com/pixelzoom> - I don't think you should drop
it, and I appreciate that you brought it to the attention of those of us
who are developing sonification wrappers. Also, I don't really see what
I've said as pushing back on the idea of avoiding string concatenation, I'm
just trying to do an honest cost-benefit analysis of the time required to
make these changes in the existing wrappers and the value that we would
gain from doing so.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/phetsims/molecules-and-light/issues/165#issuecomment-354477776>,
or mute the thread

**Comment by samreid** [comment]
I'm also having trouble rationalizing the cost-benefit analysis of the proposed work.  In my opinion, the syntax of the phetioIDs (i.e. that components are separated by dots) is *the specification* for how phetioIDs are designed.  I can understand the value in factoring out the `.` and functions for working with it, but is it really worth it if we decide the `.` will never change?  Since we agreed it is OK for clients to use fully-formed IDs in https://github.com/phetsims/tandem/issues/41#issuecomment-354188255 we know the `.` will never change.

Also, should PhET-iO clients have to know how to use a PhetioIDUtils.js library in order to create the strings they want?  Should we encourage clients to use PhetioIDUtils.append(x,y) instead of x+'.'+y?  How does this help clients?

Imagine I proposed that we needed to "factor out" camel casing for key names.  Then instead of:

```js
myObject['somePropertyName'] = 123; // Example A
```

Developers had to factor out the convention for camel casing like so:

```js
myObject[SomeUtilityLibrary.toCamelCase('some','property','name'))] = 123; // Example B
```

Example A is easier to read and understand because we all know the protocol for key names.  Does the same logic apply to phetioIDs and dots?  If not, why not?

**Comment by pixelzoom** [comment]
If you want to duplicate '.' and use string concatenation, go for it.

**Comment by samreid** [comment]
I have not heard a compelling reason for factoring it out, however, I don't think I should make a unilateral decision on this, so perhaps we should chat at an upcoming developer meeting.

**Comment by pixelzoom** [comment]
@samreid said:
> I'm also having trouble rationalizing the cost-benefit analysis of the proposed work.

I don't understand what the big cost is here. I could change all of the client sites in a fraction of the time that we've spent discussing this.

> In my opinion, the syntax of the phetioIDs (i.e. that components are separated by dots) is the specification for how phetioIDs are designed

Using knowledge about the syntax for visual inspection is fine. Writing (and duplicating) code that uses knowledge of the syntax to form or manipulate the ID is not OK.  Haven't we learned that from mistakes made with PhET's version ID?  

I'd also like to point out that implementation of this syntax is far from robust.  It's trivial to create a phetioID that breaks everything.  E.g. `tandem.createTandem( 'slider.' )`  And it's not robust because it's not encapsulated.

 > Since we agreed it is OK for clients to use fully-formed IDs in phetsims/tandem#41 (comment) we know the . will never change.

If you're using a fully-formed ID, it shouldn't matter whether the separator will change. Fully-formed means that you are given an identifier, and you don't care about the tokens that make up that identifier; it's atomic. If you're using a fully-formed ID for something, and the ID changed, then you would replace it with the new fully-formed ID, and you wouldn't care what had changed.  If you create that ID using string concatenation, then it is not fully-formed.  And if you start picking apart that fully-formed ID, then it's no longer fully-formed.

> Imagine I proposed that we needed to "factor out" camel casing for key names ...  Does the same logic apply to phetioIDs and dots? If not, why not?

I fail to see any analogy here.

**Comment by samreid** [comment]
@pixelzoom what do you think about this part?

> Also, should PhET-iO clients have to know how to use a PhetioIDUtils.js library in order to create the strings they want? Should we encourage clients to use PhetioIDUtils.append(x,y) instead of x+'.'+y? How does this help clients?

**Comment by pixelzoom** [comment]
Do PhET-iO clients create phetioIDs, or do they use phetioIDs as they appear in the API specification? If they are creating phetioIDs, please point me to examples.

**Comment by samreid** [comment]
If I understand correctly, this is an example: https://github.com/phetsims/molecules-and-light/issues/165#issuecomment-354340685

**Comment by pixelzoom** [comment]
15 var SCREEN_PROPERTY_ID = 'moleculesAndLight.moleculesAndLightScreen';
16 var MODEL_PROPERTY_ID = 'moleculesAndLight.moleculesAndLightScreen.model' ;
76 var photonEmittedPropertyID = 'moleculesAndLight.moleculesAndLightScreen.model.photons';
96 var coVibratingPropertyID = 'moleculesAndLight.moleculesAndLightScreen.model.CO.vibratingProperty';
107 var coRotatingPropertyID = 'moleculesAndLight.moleculesAndLightScreen.model.CO.rotatingProperty';

**Comment by pixelzoom** [comment]
These 5 should be what you called "full-formed" IDs. There's no "creation" of the IDs needed, they are obtained from the API specification.

```js
15 var SCREEN_PROPERTY_ID = 'moleculesAndLight.moleculesAndLightScreen';
16 var MODEL_PROPERTY_ID = 'moleculesAndLight.moleculesAndLightScreen.model' ;
76 var photonEmittedPropertyID = 'moleculesAndLight.moleculesAndLightScreen.model.photons';
96 var coVibratingPropertyID = 'moleculesAndLight.moleculesAndLightScreen.model.CO.vibratingProperty';
107 var coRotatingPropertyID = 'moleculesAndLight.moleculesAndLightScreen.model.CO.rotatingProperty';
```

There's exactly one id that requires dynamic construction (which currently has a poorly-named var):

```js
- 143 var moleculePropertyID = MODEL_PROPERTY_ID + '.' + currentMolecule + '.vibratingProperty';
+ 143 var moleculeID = PhetioIDUtils.append( MODEL_PROPERTY_ID, currentMolecule ); 
+ 144 var vibratingPropertyID = PhetioIDUtils.append( moleculeID, 'vibratingProperty' );
```

It might be useful to change `PhetioIDUtils.append` to be varargs, or add a new function for that takes varargs, so the above could be:

```js
- 143 var moleculePropertyID = MODEL_PROPERTY_ID + '.' + currentMolecule + '.vibratingProperty';
+ 143 var moleculeID = PhetioIDUtils.append( MODEL_PROPERTY_ID, currentMolecule, 'vibratingProperty' ); 
```

**Comment by samreid** [comment]
Let me try a different analogy.  Expression exchange has these lines of code:

```js
coinXBackImage = require( 'image!EXPRESSION_EXCHANGE/coin-x-back.png' );
coinXFrontImage = require( 'image!EXPRESSION_EXCHANGE/coin-x.png' );
coinXSquaredBackImage = require( 'image!EXPRESSION_EXCHANGE/coin-x-squared-back.png' );
```

The `!` symbol may change in a future version of requirejs, so we should factor it out like so (assuming for the sake of argument that requirejs supported dynamic strings):

```js
coinXBackImage = require( RequirejsUtils.appendPlugin('image','EXPRESSION_EXCHANGE/coin-x-back.png' ));
coinXFrontImage = require( RequirejsUtils.appendPlugin('image','EXPRESSION_EXCHANGE/coin-x.png' );
coinXSquaredBackImage = require( RequirejsUtils.appendPlugin('image','EXPRESSION_EXCHANGE/coin-x-squared-back.png' );
```
I am not trying to be pendantic.  I'm trying to understand the heart of your argument by looking at a similar situation.

In my opinion, the `!` in this case is part of the specification and unlikely to change and hence it is best to just code it as a literal (even though it is duplicated many times across our files).

If we do recommend our clients to use PhetioIDUtils.append, would we phrase it like this?

> Even though it is possible to use string concatenation to form `phetioID` values, we recommend that you use PhetioIDUtils.append instead in case we change the specification, format or syntax for these strings in the future.

**Comment by zepumph** [comment]
@pixelzoom said:
>If you're using a fully-formed ID, it doesn't matter whether the separator or syntax changes. Fully-formed means that you are given an identifier, and you don't care about the tokens that make up that identifier; it's a black box. If you're using a fully-formed ID for something, and the ID changed, then you would replace it with the new fully-formed ID, and you wouldn't care what has changed. If you create that ID using string concatenation, then it is not fully-formed. And if you start picking apart that fully-formed ID, then it's no longer fully-formed.


I see no difference between clients using fully-formed ids or creating the ids they need from string concatenation. Either way they depend on a stable api to not have to change their code. If the separator changes (which after discussing with @samreid yesterday I can say that it will probably never) then that's a stable api problem, and the client will need to update their code no matter the implementation. 

I see these approaches (string concat and copy pasting the id) as orthogonal strategies in wrapper development. given the following tandems:
```
sim.view.component.solution1
sim.view.component.solution1
sim.view.component.solution1

@jbphet said:
> .  .  .  I think this new requirement for not using string concatenation is a recent development (feel free to correct me if I'm wrong on this). This begs the question of whether it is worth the time and effort to go back through the sonification wrappers and rework them. So far, these wrappers have been used primarily for prototyping and demonstration purposes, and I wouldn't expect that most of them will live very long, since the ultimate goal is to move the sonification functionality into the mainline PhET sims

**Comment by pixelzoom** [comment]
@zepumph said:
> `"sim.view.component." + solution`. That seems like nicer code in the client side. 

This is misguided client code. The duplication of ``"sim.view.component."` is not relevant when the id is a "black box" specified in the API.

**Comment by samreid** [comment]
I agree with @pixelzoom's recommendation to generally use fully-formed phetioIDs where possible.

**Comment by zepumph** [comment]
Consensus

* Don't split up ids into component parts, keep them as a "black box" whenever possible.
* Use PhetioIDUtils.js in sim code
* Use PhetioIDUtils.js in our wrappers where needed, like in `active.html`
* Don't enforce or encourage use of PhetioIDUtils.js in client code. @pixelzoom recommends being silent on the issue.

**Comment by samreid** [comment]
Fixed in active.html and tested in requirejs and built.  I'll look through the rest of phet-io-wrappers to see if we need a similar change elsewhere.

**Comment by samreid** [comment]
I addressed all of the sites using `+ '.` and `.' +`, There may be other cases but in my opinion we can address those as we come across them.  @pixelzoom would you like to review?
