### ISSUE TITLE
Absorption sound?

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#236]
@jbphet and @Ashton-Morris is there an absorption sound?
I very clearly hear an emission sound, but I don't seem to hear an absorption sound.

Just listening on Master with the Step button.
I think there might be something subtle for absorption when the sim is playing, but using the Step button, I hear all other photon sound except the absorption sound.

**Comment by jbphet** [comment]
There isn't a specific sound for absorption.  I remember discussing it, but in non-paused situations, it was hard to distinguish from the rotation, glow, or vibrate sound, so we dropped it.  I don't think we had talked about the case where the user is stepping, since the looping sounds are disabled in that case.

Assigning to @terracoda and @Ashton-Morris to work out whether they feel this is something we should add.  If so, @Ashton-Morris can request that I use the previously provided absorption sound or provide a new one at his discretion.

**Comment by jbphet** [comment]
For reference, this issue is a child of #233.

**Comment by terracoda** [comment]
@jbphet, I get why it was dropped. I could hardly ever hear it. But when the sounds are uncoupled and isolated in the Step view it would be perfect to have an absorption sound that sits in contrast to the regular light source emission sound and the emitted from molecule sound.

In this way, a learner might even be able to go back and listen for it in the regular Play mode???

**Comment by terracoda** [comment]
What do you think @Ashton-Morris and @emily-phet?
The alternative would to just describe the absorption and not sonfify it, though I feel that might be a short sighted.

**Comment by emily-phet** [comment]
@terracoda I just played with the sim using the step button, and I think you're spot on. For many events, it takes the form of absorption, "action", re-emission. 

It makes practical sense to me to not have the "action" sound (vibrating, etc.) for reasons discussed before that are problematic with the looping sounds, but also makes sense to me pedagogically since the focus will be on either perceiving more step-wise the visuals or the description. 

But the absorption and re-emission initiate the start and end to the "event" of interest. They either both need to be there, or they both need to not be present. I think there would be a benefit to having both there, as it provides a strong short cue that an event of interest has started/stopped, could simplify the description (keeping it focused on the "action" that occurs between the absorption and re-emission), and will help tie the events experienced while stepping through to the events experienced at full speed. 

If an absorption sound is added to the step through experience, it needs to also be present the the sim is play at regular speed (though as discussed above, doesn't necessarily have to be highly salient at regular speed). 

I do want to point out that as much as possible, I'd like to avoid "deepening" the step through experience (so to speak), my gut is telling me that it will be beneficial in the long term (and consistent with intended use of the sim), to keep the differences experienced between the regular speed and step through options as minimal as possible, and keep the emphasis on using the sim at full speed. (Happy to discuss more about this, if that would be helpful, but just trying to be clear about the origins of my next comment...) This would indicate to me another reason to keep our approach to the absorption sound minimal - something like the approach we took to the sounds for GFL ruler (e.g., we tried some things and optimized, while also recognizing the object being represented wasn't a primary focus for the sim).

**Comment by terracoda** [comment]
@emily-phet, I agree that the Step button should be used minimally. It is there to get a detailed view to understand exactly this absorption-excitation-re-emission. In the visual Play mode, I find it somewhat difficult to notice the absorption, but in the Step mode it is much more salient.

I think it is fine to have an absorption that is difficult to hear when it is coupled with excitation, but is more clearly audible when not coupled with excitation.

I also think that the current simplified soundscape coupled with longer descriptions in the Step mode will benefit several groups of learners especially those who are blind.

I think the activities in the classroom will make it clear when the Step button is needed. As you say we don't need to make it sound like a wonderful thing to do in the descriptions.

I think leaving off the excitation sounds and leaving on the photon sounds was a great decision - the perfect way to make this mode less interesting while at the same time allowing learners to peel away a layer and to investigate deeply what is happening.

**Comment by terracoda** [comment]
@Ashton-Morris, @emily-phet, shall we just put back the absorption sound that goes with the current re-emission sound, and if needed adjust it? 

It would be great to have this sound it for next week's interviews.

**Comment by jbphet** [comment]
@terracoda - when exactly are next week's interviews?

**Comment by terracoda** [comment]
wed dec 18, 10 am eastern time

**Comment by jbphet** [comment]
I've added the sound back, but I don't like it much, and I think the "absorb-loop" was initially meant to be the sound that played as a loop whenever **any** absorption happened, and there was a bit of a misunderstanding about its intent.

I'm going to talk with @Ashton-Morris and see if we can get something a little better in time for the interviews.

**Comment by terracoda** [comment]
I'll need a dev version published when you are done.

For initial review, I can do a pull.

**Comment by jbphet** [comment]
In the 1/21/2020 Molecules & Light sound design meeting we reviewed several sounds that @Ashton-Morris created as an alternative to "absorb-loop".  We decided to go with, at least for now, the sound named "absorb-based-on-photon.mp3".  I'll integrate that sound and will publish a dev version (that will also include other changes) and will send out for review.

**Comment by jbphet** [comment]
The absorption sound has been in place for a while, and interviews have been conducted with no suggestions made for modification.  Still, it would be good to give this sound a bit of focused scrutiny during the next review meeting and make sure we are good with it.

There is a related issue that was logged about how the absorption sound is hard to distinguish from the other actions, like vibration and rotation, see https://github.com/phetsims/molecules-and-light/issues/293.  It will be good to review this sound in conjunction with that change.

The sound can be heard in context but *without* the spacing between it and subsequent molecule action sounds in [this dev version](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.37/phet/molecules-and-light_en_phet.html).

**Comment by jbphet** [comment]
Current sound approved in 3/17/2020 review meeting.
