### ISSUE TITLE
Possible to select a button that isn't being highlighted

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#248]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/461. Found with NVDA
It is possible to select a button without it being visually shown with the pink highlight. This is rather minor. Likely not confined to this instance. Occurs when moving backwards when navigating using screen reader commands rather than tab/shift+tab.
**Steps to reproduce**
1. Using the screen reader, move your focus to the molecules
2. Using screen reader controls, go back step by step until you hear it describe the UV button.
3. Press space
4. This occurs if you keep going back (selecting visible when you appear focused on UV, etc.)

**Visuals**
https://drive.google.com/file/d/1LKTeksc5pbZ5M3zNVCaIa-PZk4UnYFdI/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecules and Light‬
URL: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.21/phet/molecules-and-light_en_phet.html?ea&a11y&supportsSound
Version: 1.5.0-dev.21 2019-12-13 19:43:51 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Thanks for pointing out @KatieWoe. This is actually expected behavior and a feature of screen readers. As the user reads through with their cursor they can interact with things as they find them without having to use tab. The screen reader doesn't tell us where they are reading so we can't move the pink highlight as they read. But it correctly lets us know where focus is after they activate something and so we move the pink highlight at that point. This is standard behavior for all web content.

Back to @KatieWoe to close unless there are other concerns.
