### ISSUE TITLE
Sound: Hear if having a delay between the absorb sound and the interaction sound improves anyting

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/molecules-and-light#293]
Here is a short video example of how a little delay before the interaction would sound.

With a short delay
[absorb-with-delay-between-absorb-and-interaction-sound-example-video](https://drive.google.com/open?id=1kkUptImW5-ERvbDyxTtRXtBHdSNnNIWZ)

With no delay
[absorb-with-no-delay-between-absorb-and-interaction-sound-example-video](https://drive.google.com/open?id=177hDNOOxxZ97MuuqK_peRQVGcncSNh4X)

**Comment by Matthew-Moore240** [comment]
I kind of like it with the tiny delay

**Comment by Ashton-Morris** [comment]
I agree with Matthew. Visually it seems accurate still as well

**Comment by jbphet** [comment]
I think it is an improvement, but I think the delay needs to be kept pretty short so that it is clear that the sound corresponds to the action that is occurring.

Let's experiment with this in the 3/10/2020 sound design review meeting.  I can demonstrate different delay values over Zoom and we can decide what to go with.

**Comment by jbphet** [comment]
We experimented with this in real time for the absorb-and-vibrate case (using IR photons and CO2), and concluded that a 200 ms delay seems like an improvement.  I'll fold this in for all sounds in a more permanent way, and we can review and hopefully finalize at the next meeting.

**Comment by jbphet** [comment]
Reviewed at the 3/17/2020 meeting, approved.
