### ISSUE TITLE
Photon emitter images don't line up

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/molecules-and-light#32]
This isn't really a code review issue per se, but the images for the microwave and ultraviolet emitters don't line up with the slider.

![screen shot 2014-11-05 at 12 04 19 pm](https://cloud.githubusercontent.com/assets/3193912/4923933/c80c3b54-651e-11e4-9ba2-0066a5e98b29.png)

I'm not sure if we need new images or if we can just rescale these images. Looks like both of these images could be cropped too, since there is a bunch of extra whitespace on the left, which is throwing off how they center in the buttons.

**Comment by jessegreenberg** [comment]
New images have been added to the sim with a position offset to the slider so that it fits correctly on each photon emitter.  The new emitters now look like the following with sliders attached:

![infrared](https://cloud.githubusercontent.com/assets/6396244/5806120/5ef8c3f4-9fd3-11e4-846e-2def130f4b03.PNG)
![microwave](https://cloud.githubusercontent.com/assets/6396244/5806121/623d6d12-9fd3-11e4-9fd1-0c9ab0575b7b.PNG)
![visible](https://cloud.githubusercontent.com/assets/6396244/5806123/658950e4-9fd3-11e4-8914-df8690cf0c3f.PNG)
![ultraviolet](https://cloud.githubusercontent.com/assets/6396244/5806124/67bcfdfc-9fd3-11e4-98fa-5e13e20c0e23.PNG)

Reassigning to @arouinfar for review before closing.

**Comment by pixelzoom** [comment]
You could avoid having to address https://github.com/phetsims/molecules-and-light/issues/77 if the nozzle on the (microwave?) emitter were made wide where it connects to the housing.

**Comment by jessegreenberg** [comment]
Yes, that's very true. For now I have included a small black rectangle between photons and emitters as described in issue #77 so that photons do not appear prematurely for the microwave emitter.  If it is easy enough to redesign the microwave emitter so that the nozzle is wider, that may be the cleanest solution.  Otherwise I can look into clipping which could be better than the black rectangle.

**Comment by arouinfar** [comment]
The updated slider positions look good to me. I've sent @jessegreenberg an updated microwave source with a wider nozzle to address issue #77. It should not affect this issue, so closing.
