### ISSUE TITLE
missing assets directory

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecules-and-light#34]
Every simulation must have an assets directory, which contains the original files used to create images, audio, etc. For example, the (Illustrator? Photoshop?) file used to create images/microwave-transmitter.png should be in assets/.

**Comment by jessegreenberg** [comment]
New assets and images have been added to the sim.  Is it beneficial to keep the replaced assets in the assets directory for documentation, or should the unused files be removed?   Reassigning to @jbphet because he may know the PhET standard for this, but I can certainly replace the old assets if needed.

**Comment by pixelzoom** [comment]
Keep only the assets files that are current, delete vestigial/replaced asset files. GitHub will keep history if older files need to be resurrected. And this will make it easier for future maintainers to know which files are relevant.

**Comment by jessegreenberg** [comment]
Ok, thank you. Old and unused assets have been removed from the directory.  I am closing this issue because the new assets for this sim have been added.
