### ISSUE TITLE
Keyboard Nav Play/Pause clarification and suggestion

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#345]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/503
First: In the keyboard nav dialog box it says, "Pause or play action in Observation Window" for Alt+ K and this is in the Observation Window section. I interpreted this to mean that you had to be in the observation window to use this command. However, it does work seemingly no matter where keyboard focus is. Is this the intended behavior? Should clarifying language be added?
Second: Alt + K acts as the play/pause button. Would a similar command for the step through button be useful?

**Visuals**
![altkclarification](https://user-images.githubusercontent.com/41024075/82613997-ff08a880-9b83-11ea-8959-7656ea52732b.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecules and Light‬
URL: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.50/phet/molecules-and-light_all_phet.html?zoom=true
Version: 1.5.0-dev.50 2020-05-12 15:11:56 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by terracoda** [comment]
@KatieWoe, yes a hot key for Step Forward was suggested in interviews and we implemented that right after submitting the Dev test. The latest Keyboard Shortcuts dialog includes ALT + L to Step Forward in bigger steps which is really helpful for non-visual Step Forward. 

Both shortcuts are indeed "global" in nature. They were implemented to allow learners their keep attention on what is happening with the molecule, rather than forcing them to navigate to the Pause/Play/Step buttons.

From a non-visual perspective, the entire Play Area is the Observation Window. The only action that really happens (i.e., is meant to be observed) in this sim, is what is happening with the molecule in the Observation Window. The instruction for the shortcut is meant to help learners understand what they are pausing, and not about where their keyboard focus is currently. Where their focus is should already be clear from their intentional movements through the sim.

I don't think we need to change it.

**Comment by terracoda** [comment]
Very astute of you @KatieWoe to catch this, apologies this update to the Keyboard Dialog was not included in the Dev Test, though the behaviour should be, I think.
![Screen Shot 2020-05-12 at 3 04 34 PM](https://user-images.githubusercontent.com/1902116/82662824-22296b80-9c09-11ea-915b-ce7eca79aec3.png)

**Comment by jessegreenberg** [comment]
@KatieWoe do you think this addresses your concerns and can this be closed?

**Comment by KatieWoe** [comment]
Yup
