### ISSUE TITLE
Molecule names have more room for max width

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#348]
**Test device**
Lovelac
**Operating System**
ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/503. Occurs in published version. Not limited by platform.
When using stringTest=double, the strings for the different molecules are limited to the size of the original name. This can make them quite short, and with plenty of room in some cases to potentially expand. As is, the text can almost be too small to see.

**Visuals**
![maxwidthmoreroom](https://user-images.githubusercontent.com/41024075/82709736-7d298580-9c3e-11ea-846a-06c4bdaa17b8.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecules and Light‬
URL: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.50/phet/molecules-and-light_all_phet.html?zoom=true
Version: 1.5.0-dev.50 2020-05-12 15:11:56 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, I can appreciate this.

The current implementation keeps the same spacing between text and icon no matter what the length of the text is, and scales the text down to fit.

In my opinion, it isn't worth adding complexity to reduce the spacing if the text label is wider for i18n. Especially since this test is not realistic, translated labels will not double the molecular name AND the molecular formula.

@arouinfar can you please review this issue and let me know if you think work is required here?

**Comment by arouinfar** [comment]
I agree with @jessegreenberg.

MAL has been translated into more than 50 locales, and the smallest the strings get is in Mongolian, locale code `mn`. I think these strings are still very readable.

![image](https://user-images.githubusercontent.com/8419308/82936127-5b384780-9f4b-11ea-91bb-0668d98bc220.png)
