### ISSUE TITLE
missing doc directory

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecules-and-light#35]
Every sim should have a doc directory that contains model.txt (high-level model description) and implementation-notes.txt (implementation overview for developers).  See for example beers-law-lab/doc/.

**Comment by pixelzoom** [comment]
Pinging @jbphet again to please review model.txt for molecules-and-light.

**Comment by pixelzoom** [comment]
Pinging @jbphet again to please review model.txt for molecules-and-light.

**Comment by jbphet** [comment]
I reviewed this last week in person with @jessegreenberg.  I just checked the files, and I don't see the updates I discussed with him, so I'll add my comments here.

model.txt
+ There is some good information in the original Molecules and Light Teacher Tips document that should be folded into model.txt.  Particularly, the information in the section entitled "Important modeling notes / simplifictions" should be included.  I will email the PDF version of this document to @jessegreenberg in case he isn't set up to access the old SVN repository.
+ Formatting is weird on model.txt - everything is indented.  Shouldn't be.

implementation-notes.txt
+ Information (just a link) on how to get the code for the Java version should be added.
+ The greenhouse sim is mentioned, which would be potentially confusing, since it doesn't exist in github.  This should be rewritten to make it clear that the Java version shared this, and when the greenhouse sim is ported, the same will be true, and the directories are structured to support this plan.
+ Specific reference points shouldn't be mentioned - this creates a maintainability issue.  Please remove such references and describe the issue more generally.

**Comment by jbphet** [comment]
Assigning to @jessegreenberg to address the comments above.

**Comment by jessegreenberg** [comment]
I have added and refined the information in model.txt and implementation-notes.txt as described above.    For the original Java, should the link direct to Unfuddle or to the sim location in phet.colorado.edu?

Reassigning to @jbphet for review.

**Comment by jbphet** [comment]
Just reviewed this with @jessegreenberg and it all looks good.  Closing.
