### ISSUE TITLE
(Suggestion) Gradient the color of the bulb to match the shade of the slider's location.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/molecules-and-light#88]
I just noticed that the bulb's only have two settings, on and off. Perhaps have the color of the bulb match the location of the slider? Looks ascetically strange is all.

Visible Light off
![screen shot 2015-02-19 at 9 27 03 am](https://cloud.githubusercontent.com/assets/5631059/6270779/93fbccc8-b819-11e4-840e-533e60ba114b.png)
Very small increment of the slider
![screen shot 2015-02-19 at 9 27 11 am](https://cloud.githubusercontent.com/assets/5631059/6270782/97629338-b819-11e4-94a3-10d462a6f93f.png)
UV Light off
![screen shot 2015-02-19 at 9 26 13 am](https://cloud.githubusercontent.com/assets/5631059/6270785/9b4148aa-b819-11e4-93a2-5f3c55abb468.png)
Very small increment of the slider
![screen shot 2015-02-19 at 9 26 55 am](https://cloud.githubusercontent.com/assets/5631059/6270788/9d48724a-b819-11e4-8236-a49112ef9c2a.png)

**Comment by jessegreenberg** [comment]
I think this can be done.  Assigning to @arouinfar because this is more of a design decision.

In order to have dynamic colors, we will need to draw the bulbs with scenery rather than load in images.  The photon emitter housing can still be loaded in as an image.

@arouinfar, what do you think about this feature?

**Comment by arouinfar** [comment]
I've emailed @jessegreenberg artwork for the photon sources with the bulbs removed.

**Comment by jessegreenberg** [comment]
The photon emitter bulb color now changes with photon emission frequency.  This change is published in dev.6.  Assigning to @arouinfar for review.

I had a difficult time getting the shading to match the old mockups exactly.  If you need me to tweak some colors or change anything please let me know.

**Comment by arouinfar** [comment]
I think it looks pretty good, @jessegreenberg. I'm going to leave this issue open until after my interviews this week. If all goes well, I'll close the issue.

**Comment by jessegreenberg** [comment]
I just noticed that this feature performs very poorly on iPad2.  I will look into a better way of implementing this.

**Comment by jessegreenberg** [comment]
I just met with @jbphet and we discussed a better way of implementing this feature.  I will work on this and it will be published in a new dev version soon.

**Comment by arouinfar** [comment]
I didn't notice any issues during my interview this afternoon, so I'll reassign to @jessegreenberg to implement the change necessary address the performance issues.

**Comment by jessegreenberg** [comment]
I have just published dev.7 with a new method of implementing this feature.  Instead of drawing the new bulbs with scenery, 'on' and 'off' emitters are layered and opacity of the 'off'' emitter is set by the emission frequency.

This performs much better on iPad2.  The original 'on' and 'off' emitter images are used so the emitters look exactly like the mockups.

Assigning to @arouinfar to review how this looks now.

**Comment by arouinfar** [comment]
It looks great! Thanks, @jessegreenberg.
