### ISSUE TITLE
Long load times on Ipad2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molecules-and-light#89]
This sim suffers from long loading times on iPad2.  I observe a loading time of around 16 seconds.

I believe this is caused by the ChirpNode in SpectrumWindow, which is expensive in calculating points to draw along the curve.  The chirp is drawn at sim launch so that it doesn't have to be redrawn every time the user presses the "Show Light Spectrum" button.  This causes long loading times at sim startup.

**Comment by jessegreenberg** [comment]
Reducing the calculations comes at a cost to resolution of the chirp node.  Perhaps a solution would be create a new image representing the chirp and load it into the sim.  No calculations would be necessary this way.

**Comment by jessegreenberg** [comment]
Just met with @jbphet to discuss this.  Removing chirpnode does not save too much time.

Leaving this open for now, but the issue seems to be something specific for dev version dev.6.

**Comment by jessegreenberg** [comment]
I just published dev.7 and I still observe loading times in the range of 14-16 seconds.

**Comment by jessegreenberg** [comment]
As of version dev.9, long loading times are still observed for iPad2 (iOS 8.2 ).  I notice that removing the observation window reduces loading time significantly.  I manually measured loading times with and without the observation window included in the scene:

With observation window included:
* 16.48 s
* 16.67 s
* 16.37 s

With Observation window removed:
* 6.12 s
* 6.21 s
* 6.40 s

Removing the observation window saves about ten seconds of loading time on iPad2

**Comment by jbphet** [comment]
Below is a screen shot of a flame chart captured while loading this sim in Chrome+Win7.  This was done using the RequireJS version from the current master so that full method names are shown, but I manually compared this to the chart from the same test run on a recent built version, and the charts are pretty comparable.  In this chart, the creation of the SpectrumWindow takes a lot of the time.  This is probably not too surprising, since the elements in this window are created in code using some fairly elaborate operations.  We should try a test where this window is removed.  If this significantly decreases load time, we should look at using the new "mipmapping" capabilities of Scenery to provide some of the more complex portions.  We can't replace the entire diagram with this due to the need to support translation, but we could replace the graphical portions, which might save a lot of time.

![mal-flame-chart-1](https://cloud.githubusercontent.com/assets/3082831/6676671/51bc4b82-cbef-11e4-8470-adfd641bf868.png)

**Comment by samreid** [comment]
@jbphet better ask @jonathanolson because I think there is a simple way to trigger scenery not to compute stroke bounds--could speed everything up with minimal effort and keeping everything in nice maintainable scenery code instead of a separate image.

**Comment by samreid** [comment]
Or dynamically create the spectrum window after the sim has started?

**Comment by pixelzoom** [comment]
> the creation of the SpectrumWindow takes a lot of the time.

How much time, on what platforms?

**Comment by jessegreenberg** [comment]
The loading times are very long on iPad2 and iPad3.  I manually measured the loading time as shown above and it is an average of about 16 seconds on iPad2.

I also measured the load time on iPad2 when the spectrum window is removed and the load time is reduced by about 10 seconds.  I can do a test of what the wait time would be if we dynamically create the window when the button is pressed.

**Comment by jbphet** [comment]
If removing the screen reduces the load time by 10 seconds, I'm guessing it would probably take around 10 seconds to generate it dynamically, which would be prohibitively long.  Let's first try looking at turning off bounds computation, as @samreid suggests above, and if that doesn't help let's start figuring out which portions of the spectrum window take the most time to create and investigate replacing those portions with mipmapped images.

**Comment by jonathanolson** [comment]
Just pushed improvements that speed up the computation of stroked line bounds.

**Comment by jbphet** [comment]
@jessegreenberg and I just did some testing and found that much of the long load time is due to the chirp node, even though in earlier testing it didn't seem to be a big deal.  Not sure what has changed, or if our original methodology was flawed, but in testing on an iPad 2 running iOS8, removing the node reduced load time by 10 seconds.  Reducing the number of points defining the node from 2000 to 1000 reduced load time by roughly 7 seconds.  At 500 points, load time was around 8 seconds, but the chirp was starting to look pretty ragged. Jesse is going to look at two possibilities:
+ changing the algorithm to always have points at the peaks of the sine wave
+ generating the line using quadratics

Meanwhile, I will
+ quantify the improvements that result from the changes to Scenery (see comment immediately above)
+ look at optimization of bounds computation

**Comment by jbphet** [comment]
Just tested v1.0.0-dev.10 on iPad 2 iOS 7.0.4 and iPad 3 iOS 8.1 and load times are consistently around 5 seconds, which is quite good.  This seems to be addressed.  Closing.
