### ISSUE TITLE
Bonds are in incorrect locations on iPad

### ISSUE THREAD

**Issue by jbphet** [phetsims/molecules-and-light#96]
The screenshots below illustrate the issue.  This was seen on an iPad 2 running iOS 7.0.4 and an iPad 3 running iOS 8.something.  The odd looking bonds are fairly obvious when the sim is running, but can be captured as shown below by pausing the sim when molecules are flying apart or rotating.

![mal-broken-bonds-1](https://cloud.githubusercontent.com/assets/3082831/6604126/0f679a40-c7ec-11e4-8585-61fb821d17bf.PNG)

![mal-broken-bonds-2](https://cloud.githubusercontent.com/assets/3082831/6604130/16f53ea2-c7ec-11e4-954a-a6c18c5fd258.PNG)

**Comment by jessegreenberg** [comment]
This issue is slightly observable in Chrome with water atoms.  For vibration and rotation behaviors, one can see that the atomic bond positions lag slightly behind the position of atoms.
It is easiest to see while using the pause button once the water molecule has absorbed an infrared or microwave photon.

![capture](https://cloud.githubusercontent.com/assets/6396244/6635152/ee35f5a0-c927-11e4-9b96-2947469e0ee4.PNG)

**Comment by jessegreenberg** [comment]
This issue is resolved with the commit above, I can no longer reproduce when I test on Chrome and iPad2 (iOS 8.1.3).  

When the molecule moves, all atom positions change so I thought I could get away with linking the atomicBondNode update function to just one of the atom positions. But the update function needs to get called when either atom moves so that the atomic bonds are locked in the right position.

**Comment by jbphet** [comment]
I just tested this against the master branch, and it looks good.  Closing.
